# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://sementeurbana.com
title: Semente Urbana
email: joejvogel@gmail.com
author: Joe Vogel
description: > 
  Semeando um novo futuro. A Semente Urbana visa prover soluções físicas e digitais necessárias para abastecer suas comunidades de produtos frescos todo o ano além de capacitar indivíduos e organizações para tornar este processo o mais produtivo possível.
copyright: 'Copyright &copy; 2018 Semente Urbana. All Rights Reserved.'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Facebook
    url: https://www.facebook.com/SementeUrbanaOficial
  - title: Instagram
    url: https://www.instagram.com/sementeurbanaoficial/
